name: cafetariat
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.7.0
  firebase_auth: ^5.3.2
  cloud_firestore: ^5.4.5
  provider: ^6.1.2
  flutter_bloc: ^8.1.6
  lottie: ^3.1.3
  flutter_riverpod: ^2.6.1
  flutter_form_builder: ^9.5.0
  printing: ^5.13.4
  pdf: ^3.11.1
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/pics/affiche1.png
