// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALXVt26DzzyYsvydOS3pozcu92iiQMvcA',
    appId: '1:80806741303:web:d34302ca9491f95225c6b2',
    messagingSenderId: '80806741303',
    projectId: 'coffeehouse-efcd8',
    authDomain: 'coffeehouse-efcd8.firebaseapp.com',
    storageBucket: 'coffeehouse-efcd8.firebasestorage.app',
    measurementId: 'G-0FRW4JJ3X5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6DVuQS7LVc3O3TzLbFp-nnqQciC01K_0',
    appId: '1:80806741303:android:a956c56f41acc01625c6b2',
    messagingSenderId: '80806741303',
    projectId: 'coffeehouse-efcd8',
    storageBucket: 'coffeehouse-efcd8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDI1DOV2LXQcpb367TcvK5932UoY5AYltM',
    appId: '1:80806741303:ios:887fd892034b167e25c6b2',
    messagingSenderId: '80806741303',
    projectId: 'coffeehouse-efcd8',
    storageBucket: 'coffeehouse-efcd8.firebasestorage.app',
    iosBundleId: 'com.example.cafetariat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDI1DOV2LXQcpb367TcvK5932UoY5AYltM',
    appId: '1:80806741303:ios:887fd892034b167e25c6b2',
    messagingSenderId: '80806741303',
    projectId: 'coffeehouse-efcd8',
    storageBucket: 'coffeehouse-efcd8.firebasestorage.app',
    iosBundleId: 'com.example.cafetariat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALXVt26DzzyYsvydOS3pozcu92iiQMvcA',
    appId: '1:80806741303:web:e1347828fe70834a25c6b2',
    messagingSenderId: '80806741303',
    projectId: 'coffeehouse-efcd8',
    authDomain: 'coffeehouse-efcd8.firebaseapp.com',
    storageBucket: 'coffeehouse-efcd8.firebasestorage.app',
    measurementId: 'G-PZDE4V1RTL',
  );
}
